version: '3.4'

services:
  tstapi:
    image: tstapi
    build:
      context: .
      dockerfile: ./Dockerfile
  db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - name=value
    volumes:
      - ./data:/data/db
